import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
// componet
import Navbar from "./components/navbar/navbar";
import ClientOnly from "./components/ClientOnly";
import ToastProvider from "./providers/ToastProvider";

// custom modal
import RegisterModal from "./components/modals/RegisterModal";
import LogInModal from "./components/modals/LogInModal";

import getCurrentUser from "./actions/getCurrentUser";
import NextAuth from "next-auth";
import { NextAuthProvider } from "./provider";
import RentModal from "./components/modals/RentModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ClientOnly>
            <ToastProvider />
            <LogInModal />
            <RentModal />
            <RegisterModal />
            <Navbar currentUser={currentUser} />
          </ClientOnly>
          <div className="pt-28 pb-20">{children}</div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
